
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 7
#define YY_END_OF_BUFFER 8
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[207] =
    {   0,
        0,    0,    8,    6,    6,    1,    6,    6,    6,    6,
        0,    0,    0,    0,    0,    0,    0,    0,    2,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    2,    0,
        0,    0,    0,    0,    0,    3,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    4,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    4,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    5,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    5,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    1,    1,    6,
        1,    6,    1,    1,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        1,    1,    1,    1,    6,    1,    8,    9,   10,   11,

       12,   13,    7,    7,   14,    7,    7,   15,   16,   17,
        7,   18,    7,   19,   20,   21,   22,   23,    7,   24,
        7,    7,   25,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[26] =
    {   0,
        1,    2,    3,    1,    1,    4,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    5
    } ;

static yyconst flex_uint16_t yy_base[230] =
    {   0,
        0,   17,  317, 1541,   34,   51,    2,  301,  301,    2,
        0,    0,  299,  299,    4,  297,  296,    5,    0,  301,
      291,  293,  297,  297,  287,    8,   11,  298,    0,  282,
      293,  277,  284,  278,  285, 1541,  272,  276,  281,  274,
      266,  269,   14,   29,  262,  272,   26,   31,   40,   46,
      269,   43,   48,   55,   64,   49,   69,   80,   93,  106,
      130,   39,   72,   77,  154,   66,  177,  201,  225,  254,
      252,    0,   61, 1541,   66,   79,  249,  249,   98,  112,
      269,  293,   74,   78,  247,  114,  317,  341,  249,   98,
      248,  365,  388,  412,   14,  232,  225,  110,  436,  460,

      104,  101,  229,  121,  484,  508,  532,  216,  211,  556,
      567,  591,  615,  639,  663,   95,  119,  127,  146,  687,
      711,  144,  148,  735,  150,  759,  783,  157,  200,  181,
        0,  146, 1541,  140,  147,  115,  165,  174,  807,  831,
      174,    0, 1541,  160,  183,  185,  855,  879,  903,  171,
      148,  187,  189,  191,  927,  185,  204,  951,  975,  179,
      188,  216,  999,  157,  218, 1023, 1047,   49,   90, 1071,
      211, 1095, 1119,  210,  201, 1143,  212, 1167, 1191, 1215,
       87, 1239, 1263, 1287, 1311, 1335,   64,    0,  199,  217,
     1359, 1383,   16,    0,  242,  244, 1407,  229,  252,  254,

     1431,  256,  260,  262,  272, 1541, 1456, 1461, 1466, 1470,
     1472, 1474, 1477, 1480, 1482, 1486, 1490, 1494, 1497, 1501,
     1505, 1509, 1511, 1515, 1519, 1523, 1527, 1531, 1535
    } ;

static yyconst flex_int16_t yy_def[230] =
    {   0,
      207,  207,  206,  206,  206,  206,  206,  206,  206,  206,
        5,    6,  206,  206,  206,  206,  206,  208,  209,  206,
      206,  206,  206,  206,  206,  208,  208,  206,  209,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  210,  206,
      206,    6,  211,  206,  212,   52,  213,  214,  212,  215,
      215,   61,  206,  213,  213,  216,  216,  216,  214,   61,
       61,   61,   61,  206,   61,   61,  206,  213,  206,  216,
      216,  216,   61,   61,  206,  213,  216,  216,   61,   61,
      206,  213,  216,  216,   61,   61,  206,   92,  216,  216,

       61,   61,  206,   92,  216,  216,  217,   61,  206,  218,
      219,  216,  220,  221,  221,  115,   61,  222,  222,  223,
      223,  222,  224,  216,  224,  224,  224,   69,  115,  115,
      115,  115,  206,  115,  115,   61,  222,  225,  225,  206,
      121,  121,  206,  121,  206,  224,  216,  224,  224,  115,
      115,   61,  206,  225,  225,  121,  216,  224,  224,  115,
      115,   69,  225,  121,  214,  224,  224,  115,  115,  225,
      121,  224,  224,  115,  115,  225,  121,  224,  224,  226,
      115,  225,  227,  228,  224,  220,  115,  115,  115,  115,
      229,  222,  121,  121,  222,  224,  224,  115,  222,  225,

      224,  115,  224,   69,  214,    0,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206
    } ;

static yyconst flex_uint16_t yy_nxt[1567] =
    {   0,
      206,    5,    6,  206,    7,   18,   19,   27,   28,    8,
       27,   28,    9,   27,   28,   49,   49,   10,    5,    6,
       22,    7,   22,   23,  101,   23,    8,   53,   53,    9,
       50,   50,   54,   54,   10,   11,   12,   71,   16,  141,
       16,   49,   49,   13,   56,   56,   14,   50,   50,   53,
       53,   15,   12,   12,   76,   13,   54,   54,   13,  174,
       16,   14,   71,   17,   16,   58,   58,   79,   79,   59,
       63,   63,  130,   63,   63,   61,   76,   62,   63,   63,
       65,   58,   58,   77,   71,   89,   83,  130,   65,   71,
       74,   67,   90,   68,   58,   58,   84,   71,   59,   79,

       79,   71,   71,  190,   61,  175,   62,   69,   69,   96,
      135,   70,  108,   79,   79,   63,   63,   72,  130,   73,
      104,   71,   74,  107,   71,   92,   64,   71,  137,  137,
       74,   69,   69,   64,  152,   70,   74,   64,   71,  136,
      110,   72,   71,   73,   64,  122,  122,  119,  119,  145,
      145,  145,  145,   75,   74,   63,   63,  139,  128,  128,
      150,  135,  161,  130,  151,   65,  137,  137,   74,  130,
      130,  130,  133,  171,  133,  153,  153,   78,   79,   79,
      156,  133,  160,  141,  145,  145,  145,  145,  162,  162,
      153,  153,  153,  153,  130,  168,  164,  141,  143,  169,

       81,   74,   79,   79,  130,  165,  165,  133,  141,  133,
       71,  130,  181,  143,  135,  143,   82,  162,  162,  165,
      165,  177,  130,  130,  130,   74,   69,   69,   74,  180,
      118,  183,  117,  130,  141,  141,   67,  198,   68,  109,
      130,  103,   74,  195,  195,  145,  145,  102,  202,   74,
       63,   63,  130,  199,  199,  153,  153,  204,  204,   97,
       65,  205,  205,  204,  204,   95,  133,   91,  133,   86,
       79,   79,   85,  205,  205,   71,  143,   71,  143,  130,
       52,   52,   51,   48,  133,   47,  133,   46,   45,   87,
       44,   43,   42,   74,   79,   79,  133,   41,   40,   39,

       38,   37,   36,   35,   34,   33,   32,   31,   30,   25,
       88,   24,   21,   20,   21,   20,  206,   74,   79,   79,
      206,  206,  206,  206,  206,  206,  206,  206,   93,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,   74,   79,   79,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,   94,  206,  206,  206,  206,
      206,  206,  206,  206,  206,   74,   63,   63,  206,  206,
      206,  206,  206,  206,  206,  206,   65,  206,  206,  206,
      206,   98,  206,  206,  206,  206,  206,  206,   78,   79,
       79,  206,  206,  206,  206,  206,  206,  206,  206,  206,

      206,  206,  206,  206,   99,  206,  206,  206,  206,  206,
      206,  206,   74,   79,   79,  206,  206,  206,  206,  206,
      206,  206,  206,  100,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,   74,   79,   79,  206,
      206,  206,  206,  206,  206,  206,  105,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
       74,   79,   79,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  106,  206,  206,  206,  206,
      206,  206,  206,  206,   74,   79,   79,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,

      206,  206,  206,  111,  206,  206,  206,  206,   74,   79,
       79,  206,  206,  206,  206,  206,  206,  206,  206,  112,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,   74,  113,  113,  206,  206,   70,  206,  206,
      206,  206,  206,  115,  206,  116,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,   74,  119,  119,  206,
      206,   64,  206,  206,  206,  206,  206,  121,  122,  122,
      206,  206,   80,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,   74,   79,   79,  206,  206,  206,  206,  206,  206,

      206,  206,  206,  206,  206,  206,  206,  124,  206,  206,
      206,  206,  206,  206,  206,   74,  113,  113,  206,  206,
      206,  206,  206,  206,  206,  206,  126,  206,  127,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,   74,
      128,  128,  206,  206,  129,  206,  206,  206,  206,  206,
      131,  206,  132,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  133,  128,  128,  206,  206,  129,  206,
      206,  206,  206,  206,  131,  206,  132,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  134,  133,  140,  140,
      206,  206,  206,  206,  206,  206,  206,  206,  142,  206,

      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  143,  140,  140,  206,  206,  206,  206,  206,  206,
      206,  206,  142,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  144,  143,   79,   79,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  147,  206,  206,  206,   74,
      145,  145,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  148,  133,  145,  145,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  149,  206,

      206,  206,  206,  206,  206,  206,  206,  133,  153,  153,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      155,  143,  140,  140,  206,  206,  206,  206,  206,  206,
      206,  206,   77,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  143,   79,   79,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  157,  206,  206,  206,  206,   74,
      145,  145,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  158,

      206,  206,  206,  133,  145,  145,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      159,  206,  206,  206,  206,  206,  206,  133,  153,  153,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  163,  206,  206,
      206,  143,  145,  145,  206,  206,  206,  206,  206,  206,
      206,  206,  166,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  133,  145,  145,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  167,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  133,

      153,  153,  206,  206,  206,  206,  206,  206,  206,  206,
      170,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  143,  145,  145,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  172,
      206,  206,  206,  206,  206,  206,  206,  133,  145,  145,
      206,  206,  206,  206,  206,  206,  206,  206,  173,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  133,  153,  153,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  176,  206,  206,
      206,  206,  206,  206,  206,  143,  145,  145,  206,  206,

      206,  206,  206,  206,  206,  178,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  133,
      145,  145,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  179,  206,  206,  206,  206,  206,
      206,  206,  206,  133,  153,  153,  206,  206,  206,  206,
      206,  206,  206,  182,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  143,  145,  145,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  184,  206,  206,  206,
      206,  133,  145,  145,  206,  206,  206,  206,  206,  206,

      206,  206,  185,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  133,  186,  186,  206,  206,
      129,  206,  206,  206,  206,  206,  188,  206,  189,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  133,
      153,  153,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  191,  206,
      206,  206,  206,  143,  192,  192,  206,  206,  141,  206,
      206,  206,  206,  206,  194,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  143,  195,  195,
      206,  206,  146,  206,  206,  206,  206,  206,  206,  206,

      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  133,  145,  145,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  197,  206,  206,
      206,  206,  206,  206,  206,  133,  186,  186,  206,  206,
      206,  206,  206,  206,  206,  206,  126,  206,  127,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  133,
      199,  199,  206,  206,  154,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  143,  192,  192,  206,  206,  206,  206,
      206,  206,  206,  206,  139,  206,  206,  206,  206,  206,

      206,  206,  206,  206,  206,  206,  206,  143,  145,  145,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  201,  206,  206,
      206,  133,  145,  145,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      203,  206,  206,  206,  206,  133,    4,    4,    4,    4,
        4,   26,   26,   26,   26,   26,   29,   29,  206,   29,
       29,   55,   55,   57,   57,   60,   60,   60,   64,   64,
       64,   66,   66,   71,   71,   71,   71,   80,   80,   80,
       80,  114,  114,  114,  114,  120,  120,  120,  123,  123,

      123,  123,  125,  125,  206,  125,  130,  130,  130,  130,
      138,  138,  141,  141,  141,  141,  146,  146,  146,  146,
      154,  154,  154,  154,  187,  187,  187,  187,  193,  193,
      193,  193,  196,  196,  196,  196,  200,  200,  200,  200,
        3,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206
    } ;

static yyconst flex_int16_t yy_chk[1567] =
    {   0,
        0,    1,    1,    0,    1,    7,    7,   18,   18,    1,
       26,   26,    1,   27,   27,   43,   43,    1,    2,    2,
       10,    2,   15,   10,   95,   15,    2,   47,   47,    2,
       44,   44,   48,   48,    2,    5,    5,   95,   44,  193,
       48,   49,   49,    5,   52,   52,    5,   50,   50,   53,
       53,    5,    6,    6,   62,   50,   54,   54,   56,  168,
        6,   56,   62,    6,   54,   55,   55,   66,   66,   55,
       57,   57,  168,   63,   63,   55,   73,   55,   64,   64,
       57,   58,   58,   63,   73,   83,   75,  187,   64,   75,
       66,   58,   84,   58,   59,   59,   76,   83,   59,   79,

       79,   84,   76,  181,   59,  169,   59,   60,   60,   90,
      116,   60,  102,   80,   80,   86,   86,   60,  116,   60,
       98,   90,   79,  101,  102,   86,   98,  101,  118,  118,
       60,   61,   61,   98,  136,   61,   80,  104,  136,  117,
      104,   61,  117,   61,  104,  122,  122,  119,  119,  123,
      123,  125,  125,   61,   61,   65,   65,  119,  128,  128,
      134,  132,  151,  134,  135,   65,  137,  137,  122,  132,
      135,  151,  123,  164,  125,  138,  138,   65,   67,   67,
      144,  128,  150,  144,  145,  145,  146,  146,  152,  152,
      153,  153,  154,  154,  150,  160,  156,  141,  138,  161,

       67,   67,   68,   68,  130,  157,  157,  145,  156,  146,
      152,  161,  175,  153,  189,  154,   68,  162,  162,  165,
      165,  171,  189,  129,  175,   68,   69,   69,  157,  174,
      109,  177,  108,  174,  171,  177,   69,  190,   69,  103,
      190,   97,  165,  195,  195,  196,  196,   96,  198,   69,
       78,   78,  198,  199,  199,  200,  200,  202,  202,   91,
       78,  203,  203,  204,  204,   89,  195,   85,  196,   78,
       81,   81,   77,  205,  205,   71,  199,   70,  200,  202,
       51,   46,   45,   42,  203,   41,  204,   40,   39,   81,
       38,   37,   35,   81,   82,   82,  205,   34,   33,   32,

       31,   30,   28,   25,   24,   23,   22,   21,   20,   17,
       82,   16,   14,   13,    9,    8,    3,   82,   87,   87,
        0,    0,    0,    0,    0,    0,    0,    0,   87,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   87,   88,   88,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   88,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   88,   92,   92,    0,    0,
        0,    0,    0,    0,    0,    0,   92,    0,    0,    0,
        0,   92,    0,    0,    0,    0,    0,    0,   92,   93,
       93,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   93,    0,    0,    0,    0,    0,
        0,    0,   93,   94,   94,    0,    0,    0,    0,    0,
        0,    0,    0,   94,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   94,   99,   99,    0,
        0,    0,    0,    0,    0,    0,   99,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       99,  100,  100,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  100,    0,    0,    0,    0,
        0,    0,    0,    0,  100,  105,  105,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,  105,    0,    0,    0,    0,  105,  106,
      106,    0,    0,    0,    0,    0,    0,    0,    0,  106,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  106,  107,  107,    0,    0,  107,    0,    0,
        0,    0,    0,  107,    0,  107,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  107,  110,  110,    0,
        0,  110,    0,    0,    0,    0,    0,  110,  111,  111,
        0,    0,  111,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  111,  112,  112,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,  112,    0,    0,
        0,    0,    0,    0,    0,  112,  113,  113,    0,    0,
        0,    0,    0,    0,    0,    0,  113,    0,  113,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  113,
      114,  114,    0,    0,  114,    0,    0,    0,    0,    0,
      114,    0,  114,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  114,  115,  115,    0,    0,  115,    0,
        0,    0,    0,    0,  115,    0,  115,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  115,  115,  120,  120,
        0,    0,    0,    0,    0,    0,    0,    0,  120,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  120,  121,  121,    0,    0,    0,    0,    0,    0,
        0,    0,  121,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  121,  121,  124,  124,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  124,    0,    0,    0,  124,
      126,  126,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  126,  126,  127,  127,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  127,    0,

        0,    0,    0,    0,    0,    0,    0,  127,  139,  139,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      139,  139,  140,  140,    0,    0,    0,    0,    0,    0,
        0,    0,  140,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  140,  147,  147,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  147,    0,    0,    0,    0,  147,
      148,  148,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  148,

        0,    0,    0,  148,  149,  149,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      149,    0,    0,    0,    0,    0,    0,  149,  155,  155,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  155,    0,    0,
        0,  155,  158,  158,    0,    0,    0,    0,    0,    0,
        0,    0,  158,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  158,  159,  159,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  159,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  159,

      163,  163,    0,    0,    0,    0,    0,    0,    0,    0,
      163,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  163,  166,  166,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  166,
        0,    0,    0,    0,    0,    0,    0,  166,  167,  167,
        0,    0,    0,    0,    0,    0,    0,    0,  167,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  167,  170,  170,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  170,    0,    0,
        0,    0,    0,    0,    0,  170,  172,  172,    0,    0,

        0,    0,    0,    0,    0,  172,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  172,
      173,  173,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  173,    0,    0,    0,    0,    0,
        0,    0,    0,  173,  176,  176,    0,    0,    0,    0,
        0,    0,    0,  176,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  176,  178,  178,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  178,    0,    0,    0,
        0,  178,  179,  179,    0,    0,    0,    0,    0,    0,

        0,    0,  179,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  179,  180,  180,    0,    0,
      180,    0,    0,    0,    0,    0,  180,    0,  180,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  180,
      182,  182,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  182,    0,
        0,    0,    0,  182,  183,  183,    0,    0,  183,    0,
        0,    0,    0,    0,  183,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  183,  184,  184,
        0,    0,  184,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  184,  185,  185,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  185,    0,    0,
        0,    0,    0,    0,    0,  185,  186,  186,    0,    0,
        0,    0,    0,    0,    0,    0,  186,    0,  186,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  186,
      191,  191,    0,    0,  191,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  191,  192,  192,    0,    0,    0,    0,
        0,    0,    0,    0,  192,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,  192,  197,  197,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  197,    0,    0,
        0,  197,  201,  201,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      201,    0,    0,    0,    0,  201,  207,  207,  207,  207,
      207,  208,  208,  208,  208,  208,  209,  209,    0,  209,
      209,  210,  210,  211,  211,  212,  212,  212,  213,  213,
      213,  214,  214,  215,  215,  215,  215,  216,  216,  216,
      216,  217,  217,  217,  217,  218,  218,  218,  219,  219,

      219,  219,  220,  220,    0,  220,  221,  221,  221,  221,
      222,  222,  223,  223,  223,  223,  224,  224,  224,  224,
      225,  225,  225,  225,  226,  226,  226,  226,  227,  227,
      227,  227,  228,  228,  228,  228,  229,  229,  229,  229,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[8] =
    {   0,
1, 0, 1, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "class.l"
#line 3 "class.l"
  #include <iostream>
  #include <string.h>
  using namespace std;
  extern int yylex();
  int classmatch=0;
  int extmatch=0;
  int comment=0;
  int lno=1;
  
  int comment_index[1024];
  int top_comment_index;

  int class_index[1024];
  int top_class_index;

  int ext_class_index[1024];
  int top_ext_class_index;

#line 922 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 25 "class.l"

#line 1142 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 207 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1541 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 26 "class.l"
{
																				lno++;
																			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 30 "class.l"
{
																				//printf("Comment: %s\n", yytext);
																				//printf("Line number: %u\n", yylineno);
                                                                                int i, val = yylineno;
                                                                                for(i=0;i<1024;i++)
	                                                                          	{
	                                                                          		if(comment_index[i] == val)
	                                                                          		{
	                                                                          			break;
	                                                                          		}
	                                                                          	}
	                                                                          	if(i == 1024)
	                                                                          	{
	                                                                          		comment_index[top_comment_index++] = val++;	
	                                                                          	}
                                                                            }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 47 "class.l"
{
																			  //printf("Comment: %s\n", yytext);
                                                                              //printf("Line number: %u\n", yylineno);
                                                                              int matchsize = strlen(yytext);
                                                                              //printf("Size of match = %d",matchsize);
                                                                              int it=0;
                                                                              int f=0;
                                                                              while(it!=matchsize)
                                                                              {
                                                                                if(yytext[it] == '\n')
                                                                                {
                                                                                  f++;
                                                                                  comment++;
                                                                                }
                                                                                it++;  
                                                                              }	
	                                                                          	f++;
	                                                                          	comment++;
	                                                                          //printf("Start =  %d\n", yylineno-f+1);
	                                                                          int i,val=yylineno-f+1;
	                                                                          while(val <= yylineno && top_comment_index < 1024)
	                                                                          {
	                                                                          	for(i=0;i<1024;i++)
	                                                                          	{
	                                                                          		if(comment_index[i] == val)
	                                                                          		{
	                                                                          			break;
	                                                                          		}
	                                                                          	}
	                                                                          	if(i == 1024)
	                                                                          	{
	                                                                          		comment_index[top_comment_index++] = val++;	
	                                                                          	}
	                                                                          }	
                                                                              //printf("Lines: %d\n", f);
                                                                            }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 83 "class.l"
{ 
                                                                              //printf("Found %s",yytext);
                                                                              //printf("Class declaration: %d\n",yylineno);
                                                                              int matchsize = strlen(yytext);
                                                                              //printf("Size of match = %d\n",matchsize);
                                                                              int it=0;
                                                                              classmatch++;

                                                                              int f=0;
                                                                              while(it!=matchsize)
                                                                              {
                                                                                if(yytext[it] == '\n')
                                                                                {
                                                                                	f++;
                                                                                  classmatch++;
                                                                                }
                                                                                it++;  
                                                                              }
                                                                              int i,j;
                                                                              int val = yylineno-f;
                                                                              for(i=0;i<=f;i++)
                                                                              {
                                                                              	for(j=0;j<1024;j++)
                                                                              	{
                                                                              		if(class_index[j]==val)
                                                                              		{
                                                                              			break;
                                                                              		}
                                                                              	}
                                                                              	if(j==1024)
                                                                              	{
                                                                              		class_index[top_class_index++] = val;
                                                                              	}
                                                                              	val++;
                                                                              }
                                                                            }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 119 "class.l"
{

                                                                              int matchsize = strlen(yytext);
                                                                              //printf("Size of match = %d",matchsize);
                                                                              int it=0;
                                                                              extmatch++;
                                                                              classmatch++;
                                                                              int f=0;
                                                                              while(it!=matchsize)
                                                                              {
                                                                                if(yytext[it] == '\n')
                                                                                {
                                                                                	f++;
                                                                                  classmatch++;
                                                                                  extmatch++;
                                                                                }
                                                                                it++;  
                                                                              }
                                                                              int i,j;
                                                                              int val = yylineno-f;
                                                                              for(i=0;i<=f;i++)
                                                                              {
                                                                              	for(j=0;j<1024;j++)
                                                                              	{
                                                                              		if(ext_class_index[j]==val)
                                                                              		{
                                                                              			break;
                                                                              		}
                                                                              	}
                                                                              	if(j==1024)
                                                                              	{
                                                                              		ext_class_index[top_ext_class_index++] = val;
                                                                              	}

                                                                              	for(j=0;j<1024;j++)
                                                                              	{
                                                                              		if(class_index[j]==val)
                                                                              		{
                                                                              			break;
                                                                              		}
                                                                              	}
                                                                              	if(j==1024)
                                                                              	{
                                                                              		class_index[top_class_index++] = val;
                                                                              	}
                                                                              	val++;
                                                                              }
                                                                            }      
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 167 "class.l"
;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 168 "class.l"
ECHO;
	YY_BREAK
#line 1382 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 207 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 207 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 206);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 168 "class.l"



int yywrap() {}
int main() {
  
  memset(comment_index, -1, 1024*sizeof(comment_index[0]));
  top_comment_index = 0;

  memset(class_index, -1, 1024*sizeof(class_index[0]));
  top_class_index = 0;

  memset(ext_class_index, -1, 1024*sizeof(ext_class_index[0]));
  top_ext_class_index = 0;

  char* filename = "input.txt";
  // open a file handle to a particular file:
  FILE *myfile = fopen(filename, "r");

  // make sure it's valid:
  if (!myfile) {
    cout << "I can't open " << filename << endl;
    return -1;
  }
  // set lex to read from it instead of defaulting to STDIN:
  yyin = myfile;
  
  // lex through the input:
  while(yylex());
  int i;
  printf("Class on lines: ");
  for(i=0;i<1024;i++)
  {
  	if(class_index[i] == -1)
  	{
  		break;
  	}
  	printf("%d ", class_index[i]);
  }
  printf("\n");

  printf("Number of lines with classes: %d\n", i);

  printf("Inherited Class on lines: ");
  for(i=0;i<1024;i++)
  {
  	if(ext_class_index[i] == -1)
  	{
  		break;
  	}
  	printf("%d ", ext_class_index[i]);
  }
  printf("\n");


  printf("Number of lines with inherited classes: %d\n", i);
  
  printf("Comment on lines: ");
  for(i=0;i<1024;i++)
  {
  	if(comment_index[i] == -1)
  	{
  		break;
  	}
  	printf("%d ", comment_index[i]);
  }
  printf("\n");
  printf("Number of lines with comments: %d\n", i);
}
